[package]
name = "http_client"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.44"
anyhow = "1.0"
httptest = "0.15.4"

tokio = { version = "1", features = ["full"] }
warp = "0.3"
pretty_env_logger = "0.4"
